### PR TITLE
Fix invalid ignore pattern for underscore files

### LINKED ISSUE #232: Paths are rendered twice when converting my schema file to `_spec_.json`
For some reason, when I rename my file to `_spec_.json`, it renders all the paths twice:

CleanShot 2022-11-28 at 14 03 23@2x

I couldn't reproduce on the example folder of the repo, though, it works well. So that might be an issue with my config. But I can't figure out what?

docusaurus.config.js:

```js
/** @type {import('@docusaurus/types').Config} */
module.exports = {
 [...]
  presets: [
    [
      'docusaurus-preset-openapi',
      /** @type {import('docusaurus-preset-openapi').Options} */
      {
        api: {
          path: 'openapi',
          routeBasePath: '/api',
        },
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          routeBasePath: '/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
}

```

Dependencies:

```json
{
"dependencies": {
    "@docusaurus/core": "2.2.0",
    "@docusaurus/preset-classic": "2.2.0",
    "@docusaurus/theme-search-algolia": "2.2.0",
    "@docusaurus/theme-common": "2.2.0",
    "docusaurus-preset-openapi": "^0.6.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "@mdx-js/react": "1.6.22",
    "@svgr/webpack": "6.5.1",
    "clsx": "1.2.1",
    "file-loader": "6.2.0",
    "prism-react-renderer": "1.3.5",
    "url-loader": "4.1.1"
  },
  "devDependencies": {
    "@algolia/client-search": "4.14.2",
    "@docusaurus/types": "^2.2.0",
    "@types/react": "18.0.25",
    "tsx": "3.12.1",
    "typescript": "4.9.3",
    "webpack": "5.75.0"
  }
}
```

### PR DESCRIPTION
**Pull request by baptisteArno**
Was discussed here: https://github.com/cloud-annotations/docusaurus-openapi/pull/107#discussion_r772093391

Closes #232

### CODE REVIEW

**Comment by bourdakos1** [comment]
Is GlobExcludeDefault used anywhere else? Can we just add **/_category_.{json,yaml,yml} to it so we don’t need to do the filtering or pushing of the _spec_ files?

**Comment by baptisteArno** [comment]
True! That should work just fine 👌

**Comment by bourdakos1** [comment]
Hmm it looks like the demo isn’t picking up the `_spec_` 🤔 

I didn’t realize the default glob is coming directly from Docusaurus, so maybe they changed their glob in a newer version?

**Comment by baptisteArno** [comment]
That's a mystery for me, I checked the file history that contains the GlobIgnore pattern, it has never changed 🤔 I'll investigate and let you know

**Comment by baptisteArno** [comment]
It's this pattern `"**/_*/**"` that excludes `_spec_.*` files.

Let's just not rely on `GlobExcludeDefault` for this source fetching. It's useless.

**Pull request merged**
