### PR TITLE
🚀 Expandable Status Code Table 

### PR DESCRIPTION
**Pull request by sserrata**
Address #10 

Uses built-in `<details />` component to support expandable status code response tables. Details component only appears for responses with content, i.e. `responses[code].content`. Change also moves response `code` and `description` to details summary section.

Changes made to `docusaurus.config.js` and `custom.css` are to help cleanup UI.

### CODE REVIEW

**Comment by bourdakos1** [comment]
Thanks @sserrata! I’ll take a closer look this weekend 😊

**Comment by bourdakos1** [comment]
Hey @sserrata, I think the detail view looks really nice! However, I have a couple of suggestions/concerns.

First, I think it would look more consistent if all status codes render in the bolder colored container. In the example below, the 400 status code is less noticeable and could be missed. Additionally, if all status items render the same way, I think we could remove the borders between them:
image

I think a "nice to have" (could be a separate PR) would be to color them green/red depending on status.

My main concern is that since the table view is now rendering on the neon background, it could cause clashes with other developers' custom css and potential readability issues. You mentioned tweaking `custom.css` to clean up the UI, this is something I would like to avoid, because it normally means that other developers with custom css would have to do the same. I think a good alternative could be making the expanded details view transparent, so it renders on the default background color like it does now, thoughts?

**Comment by sserrata** [comment]
The latest commit introduces the following changes:

* Now rendering responses details components without an enclosing table.
* Switched to using official HTTP status code descriptions to provide greater consistency and clarity.
* Moved `responses[code].description` to inside the details collapsible area.
* Now programmatically basing `details` color on what range the HTTP status code falls under.

*200-299*: `alert--success`
*>= 400*: `alert--danger`
*everything else*: `alert--warning`

Note that we identified a [bug](https://github.com/facebook/docusaurus/issues/6632) in Docusaurus CSS that overrides `alert--success` with `alert--info`.

**Comment by sserrata** [comment]
Hi @bourdakos1, we decided to go a different direction with status codes and schemas. Feel free to close this PR. I'll share our solution once it's ready. Thanks!

**Pull request closed without merging**
