### PR TITLE
feat: docusaurus v3 support

### LINKED ISSUE #264: Docusaurus 3.0 support
Adding `docusaurus-preset-openapi` to my package.json adds a dependency to docusaurus core v2.4.3. and my entire Docusaurus 3.0 project doesn't build. Are there plans to have this preset work with the Docusaurus 3.0 core components instead of Docusaurus 2.4.3?

### PR DESCRIPTION
**Pull request by sean-perkins**
Resolves #264

**What does this introduce?**

Introduces compatibility for Docusaurus v3 and MDX3 to the plugins. These changes are *not* backwards compatible. 

**Breaking Changes**

Requires Node v18+, React 18+ and Docusaurus v3+

**Additional Notes**

The MDX3 parser is extremely sensitive to the generated text output in the MDX files. For example you can run just about any generated output from the `main` branch against https://mdxjs.com/playground/ and see that it fails to parse when the contents are on a single line. The logical changes for parsing account for that formatting requirement and to escape `<=` and `>=` text usages, which also fail. 

The `fs-extra` changes aren't required, but limits how much of the infrastructure uses 3rd party dependencies. 

We should likely target this release under a new minor and update the README to note which versions support v2 vs. v3.

### CODE REVIEW

**Comment by sean-perkins** [comment]
@bourdakos1 netlify will need to be updated to use Node v18 for CI.

I ran the build locally and all unit/e2e tests pass. Let me know if you have questions, this one touched a bit.

**Review by bourdakos1 — APPROVED** [review]
Thanks! I’ll update netlify

**Comment by sean-perkins** [comment]
Ok I found one site configuration that broke, but I cannot find any reference to a change of behavior in Docusuarus' breaking changes. 

If you have a docs site configuration with the same base `routeBasePath`, the open API routes will fail to load and result in a 404.

For example with a configuration like:
```
api: {
  path: "examples/petstore.yaml",
  routeBasePath: "petstore/reference",
},
docs: {
  sidebarPath: require.resolve("./sidebars.js"),
  routeBasePath: "petstore",
  // Please change this to your repo.
  editUrl:
    "https://github.com/cloud-annotations/docusaurus-openapi/edit/main/demo/",
},
```

Navigating to `/petstore` will render the docs, but navigating to `/petstore/reference` will result in a 404, even though the debugger at `http://localhost:3000/__docusaurus/debug/routes` shows the routes are registered at that path. 

Previous to Docusaurus v3 you could have your docs at a base path and your openAPI docs generated at a sub path and both would resolve correctly.

**Comment by Kelly-Fisher-27Global** [comment]
Any update on getting this merged?

**Comment by bourdakos1** [comment]
@sean-perkins I updated the node version in netlify, can you try pushing a commit to re-run checks? Manually re-running doesn’t seem to be triggering a build for some reason.

**Comment by bourdakos1** [comment]
They succeeded in netlify but didn’t reflect here, so I’ll just ignore the errors and merge

**Pull request merged**
